### ISSUE TITLE
Email Address in image name

### ISSUE THREAD

**Issue by ghost** [themeteorchef/uploading-files-to-amazon-s3#1]
Hi, Ryan. Great tutorial. Modules and ECMA6 AND slingshot. A lot of knowledge you are generously offering. Thank you.

I was unable to log in to comment using disqus, so I moved over to github. 

Just wanted to share a thought I had.

I think someone who might be building a public-facing membership application may want to steer clear of saving users email address in the image name as I think the image name gets published to the client html in the <img src="">, so any publicly-facing files might expose the member's email address.

**Comment by themeteorchef** [comment]
Hey Brian! Appreciate you taking the time to post this here :)

Re: your thought, fully agree! Since this was behind a password wall (albeit public itself) I hoped it would be clear that the intent there was to only do that behind close doors. Going to make a note so it's clear.

**Comment by ghost** [comment]
Sounds good, ryan! I've added the meteor chef to the sites I check regularly for new articles. Thanks again for this one ;)
